# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl: ""

title: The Book of Gehn
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: ""
author: Gehn
email: ""
description: ""
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: Europe/Berlin
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Makefile', '_tests', 'Dockerfile', '_public']
git:
  branch: src
lato_font_load: true
mathjax: true
