title: The Book of Gehn
description: ""
baseurl: "/"
subtitle: ""
author: Martin Di Paola
email: "martinp.dipaola@gmail.com"

# These are the metadata that each post/page will have by default
# More metadata, optionally overriding this one, can be added per
# post/page in the post's front matter.
page_defaults:
    latex_macros: ""
    excerpt_token: "<!--more-->"
    ispost: true
