title: The Book of Gehn
description: "blog"
baseurl: "/"
subtitle: ""
author: Martin Di Paola
email: "martinp.dipaola@gmail.com"
url: "http://127.0.0.1:4000"
name_atom: "atom.xml"
name_rss: "rss.xml"
name_feed: "feed.xml"
analytics_base_url: "http://127.0.0.1:6127/img/"

# These are the metadata that each post/page will have by default
# More metadata, optionally overriding this one, can be added per
# post/page in the post's front matter.
page_defaults:
    latex_macros: ""
    excerpt_token: "<!--more-->"
    ispost: true
